### ISSUE TITLE
CASO 1: Cepo animaciones.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#1]
### Descripción del error. 
La animación de andar del personaje sigue activa al caer en la trampa del cepo, cuando en realidad no te puedes mover, incluso sin tocar la tecla ‘D’. También suenan los pasos cuando intentas avanzar cuando en realidad, no puedes.

### Pasos 

1.	Caer en la trampa del cepo
2.	Pulsar la letra ‘D’ (se escuchan los pasos) o no tocar ninguna tecla

### Captura de pantalla o vídeo
https://youtu.be/JDJ30kVPVAs

**Comment by AbelMoro** [comment]
Esto es un mala implementación de algunas cosas intentaremos arreglarlo
