### ISSUE TITLE
CASO 1: El tronco se sale del mapa.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#10]
### Descripción

Cuando el tronco llega al final de la rampa, se sale del mapa en vez de desaparecer, y sigue rodando hacia la izquierda hasta que se instancia otro tronco en su zona de spawn. Este acto se repite indefinidamente, y se podría solucionar colocando un Trigger al final de la rampa que provocase que el clon del tronco se destruyera al entrar en contacto con él.

### Pasos 

Para reproducir este error, el jugador ha de:
- Acercarse a la zona en la que aparece el tronco para ver mejor el error.
- Esperar a que respawnee y fijarse en la dirección que toma.

### Captura de pantalla o vídeo
[Tronco se sale del mapa.](https://drive.google.com/open?id=1B5xKxtrwiNBdSiOLJk8pNXHMBCzo2tFq)

**Comment by AbelMoro** [comment]
El comportamiento de los trocos ya se ha cambiado a un método menos agresivo que hace que esto ya no ocurra https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/21eb790d2be23f420e80473773ee75d02921120e https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/88cee7d4ac51919e49c1940f772800776d27c333 https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/5568b3ba3e26acae3c8053c06c787158522858da
