### ISSUE TITLE
CASO 1: La mina de proximidad no hace daño.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#11]
### Descripción

Cuando el jugador se posiciona encima de la mina con el escudo mirando hacia abajo, esta mina explota y le provoca retroceso, pero no le hace daño como se esperaba.

### Pasos 

Para reproducir este error, el jugador ha de:
- Colocarse justo encima de la mina azul.
- Poner el escudo mirando hacia abajo.

### Captura de pantalla o vídeo
[Funcionamiento de la mina azul.](https://drive.google.com/open?id=1sfQZdKxwp_bonqVPWAhR5e6wSvCmKIHY)

**Comment by AbelMoro** [comment]
Este error tiene que ver con un script concreto que afecta a la bomba y a las minas voy a cerrar este error de momento y la solución al mismo estará en el error https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/issues/3
