### ISSUE TITLE
CASO 1: La mina de proximidad estalla instantáneamente.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#12]
### Descripción

Cuando el jugador corre hacia la mina, hay veces en las que esta explota de manera instantánea.

### Pasos 

Para reproducir este error, el jugador ha de:
- Saltar encima de la mina azul.
- Comprobar que estalla instantáneamente y no hace daño.

### Captura de pantalla o vídeo

[Funcionamiento de la mina azul 2.](https://drive.google.com/open?id=1SgIhMUXkyX3uXuczVy7hwZ3ZxtosnEhy)

**Comment by AbelMoro** [comment]
Este error tiene que ver con un script concreto que afecta a la bomba y a las minas voy a cerrar este error de momento y la solución al mismo estará en el error https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/issues/3
