### ISSUE TITLE
CASO 1: El gas no aparece.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#13]
### Descripción

El gas no es visible (lo cual no tendría que suceder, pues en el plan de pruebas se indica que es verde). Dificulta el saber dónde está al principio, y luego lo has de suponer.

### Pasos 

Para reproducir este error, el jugador ha de:
- Acercarse a la zona del gas (después de la mina de proximidad).
- Ver cómo no hay nada.

### Captura de pantalla o vídeo

[El gas no aparece.](https://drive.google.com/open?id=1iXJlHknMD99lxQGVsbfPIqNixGDfg5SZ)

**Comment by AbelMoro** [comment]
Un problema con la capa de renderizado en la que se encontraban las partículas que crean el gas, ya arreglado y funcionando correctamente https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/9e7e3e3dfc3ddd7775b5d93864e48ba518a93aa7
