### ISSUE TITLE
CASO 1: El gas no mata instantáneamente. 

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#14]
### Descripción

Cuando el jugador entra en la zona del gas no muere instantáneamente como era de esperar. Si entra en contacto con el gas pero no se mueve, se queda indefinidamente dentro de esa zona. Una vez se mueve, el gas hace efecto.

### Pasos 

Para reproducir este error, el jugador ha de:
- Entrar dentro de la zona del gas y no moverse.
- Comprobar que su barra de vida ha bajado a 0 pero sigue vivo.
- Moverse para comprobar que al moverse sí hace efecto.

### Captura de pantalla o vídeo

[El gas no mata instantáneamente.](https://drive.google.com/open?id=1iXJlHknMD99lxQGVsbfPIqNixGDfg5SZ)

**Comment by AbelMoro** [comment]
Esto parece un problema parecido al de los pinchos hay que subir el daño del gas "verde" para asegurar que mate en un solo tick
