### ISSUE TITLE
CASO 1: Los pinchos no matan instantáneamente.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#15]
### Descripción

Cuando el jugador se coloca sobre los pinchos con el escudo, estos no le matan hasta después de que haya avanzado unos cuantos pasos.

### Pasos 

Para reproducir este error, el jugador ha de:
- Saltar sobre los pinchos con el escudo en marcha.
- Comprobar que tiene la vida a 0.
- Ver que puede moverse y no muere hasta dentro de unos cuantos pasos.

### Captura de pantalla o vídeo

[Los pinchos no matan instantáneamente.](https://drive.google.com/open?id=1FJLkzIogd8nn0rcQeo1QxPwJVv3EYN0h)

**Comment by AbelMoro** [comment]
Ahora lo pinchos funcionan como trigger y no bloquean al jugador, además le hacen una cantidad de daño mayor asegurando su muerte en un solo tick https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/325aa1948d29a83e1a8c2a11cede01ee04469dda
