### ISSUE TITLE
CASO 1 (Sesión Explorativa): El jugador puede entrar en las paredes.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#16]
### Descripción

El jugador puede “entrar en la pared” si corre hacia ella, ya que la animación de correr inclina al jugador hacia el muro demasiado y hace parecer que está dentro de él.

### Pasos 

Para reproducir este error, el jugador ha de: 
- Correr hacia una pared.
- Seguir corriendo aunque no pueda moverse.
- Ver cómo el sprite del jugador se sale de los límites.

### Captura de pantalla o vídeo

[El jugador entra en la pared.](https://drive.google.com/open?id=1uWL-u41cM1Ps9yAwXMPLApGiE2Ii7gT0)

**Comment by AbelMoro** [comment]
No es un error el jugador no entra en la pared, el sprite y la animación se introducen un poco dentro de la pared pero su funcionamiento es el correcto
