### ISSUE TITLE
CASO 1 (Sesión Explorativa): Caída de FPS al recibir daño.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#17]
### Descripción

Cuando el jugador recibe daño, hay lag y la pantalla coloca un efecto de recibir daño de color rojo de manera rápida y no siempre. Estos efectos de flash tan inesperados pueden llegar a producir ataques epilépticos.

### Pasos 

Para reproducir este error, el jugador ha de: 
- Ir hacia el humo gris (por ejemplo).
- Recibir daño por estar en el humo.
- Fijarse en lo que pasa en pantalla.

### Captura de pantalla o vídeo

[Humo provoca lag.](https://drive.google.com/open?id=1Z-Bamu-Mt70N4IIDBlrECJLjUTw0_J7G)

**Comment by AbelMoro** [comment]
Arreglado la sensación de "freeze" creado por un sistema poco desarrollado de "slowmotion" que se encuentra ahora desactivado y posiblemente deshechado https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/0680721add3edfa1852d7e096d2f11a886022107 los flashes de daño funcionan tal y como deben pero este error empeoraba su efecto
