### ISSUE TITLE
CASO 1 (Sesion Explorativa): El salto no funciona correctamente.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#18]
### Descripción

El salto del jugador no funciona correctamente y ha dificultado la prueba de alguno de los elementos dentro del caso 1 que incluyese la opción de esquivar (el cepo) o de saltar por encima de un elemento (el gas, las minas).

### Pasos 

Para reproducir este error, el jugador ha de: 
- Presionar la barra espaciadora.

### Captura de pantalla o vídeo

[Salto no funciona correctamente. ](https://drive.google.com/open?id=1ldf3niAoqdoDIUood83dClDoUPZevTm6)

**Comment by AbelMoro** [comment]
Un problema al recoger incorrectamente esa input de usuario, ahora el salto funciona correctamente cada vez que se pulsa la barra espaciadora https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/29618e5e2f25f8bcb2b2ae41c62382f5c5ac5448
