### ISSUE TITLE
CASO 1 (Sesión Explorativa): Sprites desconcertantes.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#19]
### Descripción

Algunos sprites o animaciones eran un poco desconcertantes, pues no sabes apreciar su tamaño (la expansión de la primera bomba o las descargas de metralla que emite después) y esto, sumado a la caída de FPS que se produce cada vez que el jugador recibe daño o se ejecuta una animación enemiga, dificulta el esquivarlas o defenderse ante ellas.

### Pasos 

Para reproducir el error, el jugador ha de:
- Acercarse a la bomba. 
- Ver la animación de explosión que tiene.

### Captura de pantalla o vídeo

[Funcionamiento de la bomba 1.](https://drive.google.com/open?id=1vU7g-oIeacAE3ppEFq0rnVSrKdDyDPv4)

**Comment by AbelMoro** [comment]
El problema de "lag" está arreglado en otra issue https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/issues/17 la bomba y sus escombros ahora cuentan con sus propios sprites y animación de explosión https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/9ff270cd7e32701a5c90d8f0f5655a795a2c2475 https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/0f58001757091f9070f959dfdc04e432f4375e24 https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/d671fdc487283420e3e1214f397464be364a68da https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/f8fbf3ebd8a0cd593b0187251147fb21a713c98d
