### ISSUE TITLE
CASO 1: Cepo no se activa al saltar / estar cerca del borde.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#2]
### Descripción

Al saltar sobre la trampa del cepo no se activa, cuando te debería atrapar y dejarte inmóvil. No depende del hecho de llevar el escudo equipado. Esto también ocurre si te posicionas lentamente sobre el mismo.

### Pasos 

1.	Saltar sobre el borde del cepo.
2.	O aproximarse lentamente al cepo

### Captura de pantalla o vídeo
![Anotación 2020-05-31 132528](https://user-images.githubusercontent.com/62644841/83351203-39bbcf00-a342-11ea-9eec-8898362197a4.jpg)

**Comment by AbelMoro** [comment]
Necesitamos testear esto con el nuevo script de movimiento

**Comment by edekadt** [comment]
Esto simplemente es por el tamaño de las cajas de colisión en juego. Los pies del personaje no son objetos físicos, y la trampa solo se cierra si se presiona el centro
Las dos soluciones que se me ocurren a mí serían:
1. Añadir una caja de colisión adicional al personaje que cubra la zona de los pies (de tal forma que la caja total tendría forma de T invertida)
2. Extender horizontalmente la caja de colisión del cepo. El problema con esto es que entonces el cepo se cerraría sobre el aire (visualmente). Esto se podría arreglar con un nuevo script que moviese el jugador al centro del cepo cuando lo activa.
De todas formas, no creo que esto sea un problema grande, si los cepos fuesen más peligrosos de lo que ya son algunas partes de los niveles serían mucho más difíciles.
