### ISSUE TITLE
CASO 1 (Sesión Explorativa): Un coleccionable no especificado.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#20]
### Descripción

Hay un sprite de check verde flotando en el aire y que tiene el mismo movimiento de oscilación que los coleccionables. No se ha especificado su función o si la tiene.

### Pasos 

Para reproducir este error, el jugador ha de:
- Ir a la zona de los pinchos.
- Colocarse sobre la plataforma flotante y mirar la esquina superior izquierda.

### Captura de pantalla o vídeo
![image](https://user-images.githubusercontent.com/62706897/83351824-94a3f500-a347-11ea-8b62-0509a55ab768.png)

**Comment by AbelMoro** [comment]
No es un error
