### ISSUE TITLE
CASO 1: Mina de contacto empuje.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#21]
### Descripción

Al estar en contacto con las minas, el empuje es mínimo o nulo
### Pasos 

1. Tocar las minas de contacto

### Captura de pantalla o vídeo
https://youtu.be/g7ArhvIgo0c

**Comment by AbelMoro** [comment]
Este error tiene que ver con un script concreto que afecta a la bomba y a las minas voy a cerrar este error de momento y la solución al mismo estará en el error https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/issues/3
