### ISSUE TITLE
CASO 1: Mina de proximidad zona de activación.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#22]
### Descripción
No aparece el rango de la mina de proximidad
### Pasos 

1. Ir a la zona donde hay minas de proximidad.

### Captura de pantalla o vídeo
https://youtu.be/63h2X5Pd98M

**Comment by AbelMoro** [comment]
Esto no es un bug ya que el nunca hablamos de mostrar el rango de la mina de proximidad pero desde luego podría ser una mejora

**Comment by AbelMoro** [comment]
No vamos a trabajar en esta mejora
