### ISSUE TITLE
CASO 1: Mina de proximidad sonido.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#23]
### Descripción

En ocasiones el sonido de las minas de proximidad no se activa.
### Pasos 
1. Una forma de reproducir el fallo puede ser estando encima de la mina al
explotar
2. Otra forma es activando la mina y alejándote un poco.

### Captura de pantalla o vídeo
https://youtu.be/Ks-3ULzIwOk

**Comment by AbelMoro** [comment]
Igual que en https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/issues/4 ya arreglado
