### ISSUE TITLE
Exploratorio: Sprite personaje.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#26]
### Descripción

Al estar delante de un punto de control la mano que sostiene el escudo y el escudo se muestran por detrás del punto de control.

### Pasos 

1.	Estar delante de un punto de control.
2.	Sacar el escudo.

### Captura de pantalla o vídeo
https://youtu.be/oAngAMRuAqM

**Comment by AbelMoro** [comment]
Esto esta arreglado en el Hito03
