### ISSUE TITLE
Exploratorio: Recoger items.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#27]
### Descripción

En ocasiones al intentar recoger el botiquín o la caja de reparación, no se cogen y hay que darle repetidas veces a la ‘E’. Suele ocurrir cuando no estás en el centro del objeto o cuando vas corriendo.

### Pasos 

1.	Estar cerca del borde del ítem.
2.	Apretar ‘E’ para recogerlo.
3.	Volver al paso 2 si no se ha recogido o moverte para estar más en le centro del ítem.
4.	Cambiar el paso 1 por ir corriendo.

### Captura de pantalla o vídeo
https://youtu.be/I-7XOhJuZy4

**Comment by AbelMoro** [comment]
Esto se puede mejorar
