### ISSUE TITLE
CASO 3: Atraviesa el suelo en las escaleras

### ISSUE THREAD

**Issue by androd27** [Proyectos1-FDI-UCM/c1920-Grupo08#28]
Descripción
En las escaleras al agacharse atraviesa el suelo
Pasos
1.Al final de la escaleras te agachas con el botón control, luego lo dejas de pulsar y te agachas nuevamente.
2 El jugador atraviesa el suelo.
Captura de pantalla o vídeo
https://www.youtube.com/watch?v=cSLamupyJIc

**Comment by AbelMoro** [comment]
Arreglado en https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/957b6875704ffc68a95d4e4859b4757fe5da0355
