### ISSUE TITLE
CASO 2: Movimiento.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#29]
### Descripción

A la hora de atravesar el mapa del caso 2 se hace complicado controlar al personaje,
así como entrar a los distintos sitios donde se debe acceder (como en la primera caja
de reparación), debido a la sensación de suelo resbaladizo, zonas muy estrechas que

limitan el movimiento del personaje y el hecho de no saltar cunado pulsas espacio, ya
sea porque hay un muro encima o un pequeño delay. Esto provoca que el personaje se
muestre por encima del terreno como se ve en la imagen.

### Pasos 

1. Intentar entrar en la zona de la primera caja de reaparición.
2. Intentar realizar el salto hacia la zona donde se encuentra la segunda caja de
reparación.
### Captura de pantalla o vídeo
https://youtu.be/tZFplWwwDHI

**Comment by AbelMoro** [comment]
El único bug real es el del salto https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/issues/18 ya arreglado, este nivel no esta en la versión final
