### ISSUE TITLE
CASO 1: Bomba empuje.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#3]
### Descripción

Una vez recibes el daño de la explosión el empuje de la bomba es nulo o mínimo, independientemente de llevar el escudo equipado.

### Pasos 

1.	Ir a la zona de la bomba y esperar el impacto.
### Captura de pantalla o vídeo
https://youtu.be/cGzsTt4ERJY

**Comment by AbelMoro** [comment]
El script que se encarga de las explosiones no está funcionando correctamente.

**Comment by AbelMoro** [comment]
El sistema a quedado simplificado las bombas y las minas funcionan ahora correctamente, las bombas no crean ningún tipo de empuje si no que matan al jugador si chocan cerca de él y en el caso de las minas el daño es menor y hacen un efecto pequeño de empuje.
