### ISSUE TITLE
CASO 3: Laser francotirador.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#32]
### Descripción

Cuando te encuentras en la zona del vídeo el láser choca sobre una
superficie invisible protegiéndote de los disparos que en realidad deberían de
impactar contra el jugador.
### Pasos 
1. Ir a la zona que se muestran en el video.

### Captura de pantalla o vídeo
https://youtu.be/Ayw3eJHOkDs

**Comment by AbelMoro** [comment]
Una zona de colisión que teníamos anteriormente para la cámara, ya arreglado
