### ISSUE TITLE
CASO 3: Reinicio tiro francotirador.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#34]
### Descripción

Al entrar y salir de las coberturas con bloques oscuros o claros no da la sensación de
que el tiempo entre disparos se reinicie o directamente no se reinicia.

### Pasos 

1. Entrar y salir de zonas con coberturas para ver el tiempo entre disparos.

### Captura de pantalla o vídeo
https://youtu.be/cdRsF7O4zjs

**Comment by AbelMoro** [comment]
Esta funcionando como se quería tal vez en las pruebas de testeo se explico mal o se erró al poner esta comprobación

**Comment by AbelMoro** [comment]
Me corrijo en lo que dij en el anterior comentario, es cierto que este no era el comportamiento deseado, aun así esta duplicado en https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/issues/33 y ya corregido

**Comment by AbelMoro** [comment]
https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/6e34dd6babcd1946c0c37742e614613cced41930
