### ISSUE TITLE
CASO 3: Francotirador y escudo.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#35]
### Descripción

El francotirador te rompe el escudo y aun así aparece en pantalla, junto a los efectos
sonoros del mismo. Mientras ocurre esto el personaje absorbe el daño y no llega a
morir teniendo la barra de vida vacía.
### Pasos 

1. Mantener el click izquierdo mantenido en todo momento.
2. Dejar que el francotirador te rompa el escudo.
3. Dejar que te quite la vida
El jugador solo morirá si deja de mantener click izquierdo

### Captura de pantalla o vídeo
https://youtu.be/gFWfX7eqyLI

**Comment by AbelMoro** [comment]
Duplicado https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/issues/7
