### ISSUE TITLE
CASO 3: Disparo francotirador.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#37]
### Descripción

Cuando te pones a cubierto en ciertas zonas con bloques oscuros no sabes si estás
cubierto ya que el láser te sigue apuntando al cuerpo sin recibir daño tras el disparo.

### Pasos 

1. Ir a las zonas que se muestran en los vídeos.

### Captura de pantalla o vídeo
Distintas zonas:
https://youtu.be/cUD0V1qnhaY
https://youtu.be/GYJM_hm_ATc

**Comment by AbelMoro** [comment]
Esta arreglado en los nuevos niveles en cualquier caso no es un bug te encuentras en una cobertura
