### ISSUE TITLE
CASO 1: Bomba sonido.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#4]
### Descripción

Al entrar a la zona de la bomba lentamente, esta explota pero no se reproduce el sonido de esta.

### Pasos 

1.	Entrar lentamente en la zona de la bomba.

### Captura de pantalla o vídeo
https://youtu.be/X1mEEwldEps

**Comment by AbelMoro** [comment]
Arreglado, el sonido solo se reproducía cuando el jugador recibía daño durante la explosión ahora funciona como debería https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/ebf3888a5c54c25659d9c2614ea5a6e5a3641866
