### ISSUE TITLE
CASO 1: Bomba daño.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#5]
### Descripción

En ocasiones, al cubrirte con el escudo y ser la onda invisible recibes daño sin saber cómo cubrirte correctamente. Lo mismo ocurre con la metralla que te impacta aun teniendo el escudo.

### Pasos 

1.	Ir a la zona de la bomba y esperar el impacto con el escudo cubriéndote la cabeza.

### Captura de pantalla o vídeo
https://youtu.be/6edISyhzxQ8

**Comment by AbelMoro** [comment]
La metralla no estaba funcionando correctamente, el comportamiento de la bomba ha cambiado un poco y la propia explosión de la misma atraviesa el escudo pero los escombros pueden ser bloqueados con el escudo desde https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/7022aba141c37ee76e986165b8facd8e88de69b9
