### ISSUE TITLE
CASO 1: Explosión de bomba.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#6]
### Descripción

La bomba explota cuando no estás en la zona de explosión de la bomba. 

### Pasos 

Ocurre de forma “aleatoria” cuando estás en la zona de la ametralladora.

### Captura de pantalla o vídeo
Segundo 4 del vídeo: https://youtu.be/7_bbQg3UJH8

**Comment by AbelMoro** [comment]
Probablemente un error al crear el nivel de pruebas?

**Comment by AbelMoro** [comment]
Esto fue un error al crear el nivel de pruebas hemos comprobado que la activación de la bomba en lo niveles actuales es la correcta
