### ISSUE TITLE
CASO 1: Ametralladora y escudo.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#7]
### Descripción

La ametralladora te rompe el escudo y aun así aparece en pantalla, junto a los efectos sonoros del mismo. Mientras ocurre esto el personaje absorbe el daño y no llega a morir teniendo la barra de vida vacía. 

### Pasos 

1.	Mantener el click izquierdo mantenido en todo momento.
2.	Dejar que la ametralladora te rompa el escudo.
3.	Dejar que te quite la vida
El jugador solo morirá si deja de mantener click izquierdo

### Captura de pantalla o vídeo
En el video se deja de pulsar click izquierdo en algunos momentos para ver que el fallo es al mantener el escudo justo antes de que se rompa.
https://youtu.be/7_bbQg3UJH8

**Comment by AbelMoro** [comment]
Estoy seguro que este bug sigue en la build actual
