### ISSUE TITLE
CASO 1: Escombro.

### ISSUE THREAD

**Issue by albgom21** [Proyectos1-FDI-UCM/c1920-Grupo08#8]
### Descripción

El enemigo escombro no aparece en pantalla.

### Pasos 

1.	Ir a la supuesta zona donde se debe testear el escombro.

### Captura de pantalla o vídeo
https://youtu.be/bjAFI75-xCQ

**Comment by AbelMoro** [comment]
Desde entonces se ha arreglado este error
