### ISSUE TITLE
CASO 1: El tronco empuja al jugador fuera del mapa.

### ISSUE THREAD

**Issue by simekons** [Proyectos1-FDI-UCM/c1920-Grupo08#9]
### Descripción

Cuando el jugador pone el escudo y choca contra el tronco desde la máxima altura de la rampa, el tronco empuja al jugador fuera del mapa (dentro del tilemap).

### Pasos 

Para reproducir este error, el jugador ha de:
- Colocar el escudo mirando hacia cualquier dirección.
- Subir sobre la rampa en la que respawnea el tronco.
- Dejarse empujar por el tronco.

### Captura de pantalla o vídeo
[Jugador fuera de límites.](https://drive.google.com/open?id=1OJw-q-U_2NYtYHagP2C5o8bNRCHm9dY-)

**Comment by AbelMoro** [comment]
El comportamiento de los trocos ya se ha cambiado a un método menos agresivo que hace que esto ya no ocurra https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/21eb790d2be23f420e80473773ee75d02921120e https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/88cee7d4ac51919e49c1940f772800776d27c333 https://github.com/Proyectos1-FDI-UCM/c1920-Grupo08/commit/5568b3ba3e26acae3c8053c06c787158522858da
